# Use the official SonarQube image as the base image
FROM sonarqube:latest

# Set the default language to English
ENV LANG en_US.UTF-8

# Copy the SonarQube configuration file to the container
COPY sonar.properties /opt/sonarqube/conf/sonar.properties
